### ISSUE TITLE
Have a `--quiet-already` when no data is passed

### ISSUE THREAD

**Issue by emilebosch** [kellyjonbrazil/jtbl#10]
```
jtbl:   Missing piped data
```
Would be nice if we can ignore this with a `--quiet` or `-q` So it doesn't output this. Sometimes our elaborate JQ pipelines result into 0 results and then just don't make a table.

**Comment by kellyjonbrazil** [comment]
Hi there - thank you for reporting this. That makes a lot of sense. I can definitely add a `-q` option to quiet warnings like that.

**Comment by kellyjonbrazil** [comment]
I have bumped to v1.3.1 on PyPi. Will update the packages and binaries in a bit.

**Comment by kellyjonbrazil** [comment]
There was a bug in the earlier versions where warnings/errors were not going to STDERR, nor were they causing the exit code to change. I fixed the bug and added the -q option, but you will now find that when there is no data to print, `jtbl` will now exit with an exit code of 1 - even when using the -q option.

**Comment by emilebosch** [comment]
Thanks Kelly! I love everything you do with JSON also the other tools like jc! Keep going!

**Comment by kellyjonbrazil** [comment]
Thanks so much!
