### ISSUE TITLE
Add changelog to PyPI package

### ISSUE THREAD

**Issue by djmattyg007** [kellyjonbrazil/jtbl#5]
It would be great if the changelog was included in the PyPI package. It's useful for when including documentation in distribution packages.

**Comment by kellyjonbrazil** [comment]
Hi - thanks for the feedback! I'll try to get that in tomorrow.

**Comment by djmattyg007** [comment]
I think it would also be useful in your other packages, jello and jellex.

Thanks for the awesome software by the way :)

**Comment by kellyjonbrazil** [comment]
For sure - I'll try to do those ASAP, too! Thanks, I really appreciate that!

**Comment by kellyjonbrazil** [comment]
I have uploaded v1.1.7 to PyPi with the CHANGELOG. Let me know if that works and then I'll get to the others on their next release cycle.

**Comment by djmattyg007** [comment]
Looks good :tada: Thank you!
